[package]
name = "gpu-tests"
version = "0.1.0"
edition = "2021"
description = "Test for the ec-gpu project"
homepage = "https://github.com/filecoin-project/ec-gpu"
repository = "https://github.com/filecoin-project/ec-gpu"
license = "MIT/Apache-2.0"
publish = false

[dev-dependencies]
criterion = "0.4"
divan = "0.1"
ec-gpu = { workspace = true, features = ["arkworks"] }
ec-gpu-gen = { path = "../ec-gpu-gen", default-features = false, features = ["arkworks"] }
fil_logger = "0.1.6"
rand = "0.8"
rayon = "1.5.3"
ark-ff = "0.5.0"
ark-ec = "0.5.0"
ark-bn254 = "0.5.0"
ark-std = "0.5.0"

[build-dependencies]
ark-bn254 = { version = "0.5.0" }
ec-gpu = { path = "../ec-gpu", features = ["arkworks"] }
ec-gpu-gen = { path = "../ec-gpu-gen", features = ["arkworks"] }

[features]
default = ["cuda", "opencl"]
cuda = ["ec-gpu-gen/cuda"]
opencl = ["ec-gpu-gen/opencl"]

[[bench]]
name = "multiexp"
harness = false

[[bench]]
name = "small_scalars"
harness = false
